name: mnist-vae
base: core22
version: '0.0.0'
summary: MNIST-VAE Experiment App
description: |
  MNIST-VAE Experiment App that allows users to change parameters at runtime
  and upload models of their own making.

grade: stable # devel must be 'stable' to release into candidate/stable channels
confinement: strict # devmode use 'strict' once you have the right plugs and slots


apps:
  mnist-vae:
    command: MNIST-VAE
    plugs:
      # Needed for keyring.
      - password-manager-service
      - home
      - network
      - opengl
      - x11
      - hardware-observe
      - network-bind
    environment:
      # Note: Missing ptxas bin and nvvm paths.
      LD_LIBRARY_PATH: $SNAP/_internal/nvidia/cublas/lib:$SNAP/_internal/nvidia/cuda_cupti/lib:$SNAP/_internal/nvidia/cuda_nvcc/lib:$SNAP/_internal/nvidia/cuda_runtime/lib:$SNAP/_internal/nvidia/cudnn/lib:$SNAP/_internal/nvidia/cufft/lib:$SNAP/_internal/nvidia/cusolver/lib:$SNAP/_internal/nvidia/cusparse/lib:$SNAP/_internal/nvidia/nccl/lib:$SNAP/_internal/nvidia/nvjitlink/lib:$SNAP/_internal:$LD_LIBRARY_PATH
    
parts:
  mnist-vae:
    source: local
    plugin: nil
    override-build: |
      cp -r ./* $SNAPCRAFT_PART_INSTALL/
    stage-packages:
      - libxcb1


